name: Build Artifact Test

on:
  workflow_dispatch:

permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: GitFetch
      run: git fetch -p
   
    - name: GitCheckout
      run: git checkout master_20231026
    
    - name: GitBranch
      run: git branch
    
    - name: Build the Docker image
      run: docker build . --file sample_python/Dockerfile -t python-image

    - name: DcImg
      run: docker images

    - name: DcSave
      run: |
        docker save python-image | gzip > python-image.tar.gz

    - name: DcSave
      run: |
        split -b 200M -d python-image.tar.gz
        ls -lrt

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: FilePath
         path: python-image.tar.gz
