name: Build Artifact Test Bak

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Pwd1
      run: |
        pwd

    - uses: actions/checkout@v3

    - name: Pwd2
      run: |
        pwd

    - name: GitFetch
      run: git fetch -p

#    - name: GitMerge
#      run: git merge origin/master_20231026
#      run: git merge origin/master
    
    - name: GitCheckout
      run: git checkout master_20231026
    
    - name: GitBranch
      run: git branch
    
    - name: Build the Docker image
#      run: docker build . --file /home/runner/work/test20231024/test20231024/sample_python/Dockerfile -t python-image
      run: docker build . --file sample_python/Dockerfile -t python-image

    - name: DcImg
      run: docker images

    - name: DcSave
#      run: docker save python-image | gzip > /home/runner/work/test20231024/test20231024/python-image2.tar.gz
      run: |
        docker save python-image | gzip > /home/runner/work/test20231024/test20231024/python-image3.tar.gz
        ls -lrt

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#         name: FilePath
#         path: /home/runner/work/test20231024/test20231024/python-image2.tar.gz
