name: CI        #Workflow の名前何でもOK

#on:             #実行されるタイミングを設定
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:           #以下が実行される内容
   run-ssh:
     runs-on: ubuntu-latest
     steps:
       - name: Install SSH key
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.PRIVATE_KEY }}
           known_hosts: ${{ secrets.KNOWN_HOSTS }}
           name: github-actions
           config: |
             Host server
               HostName ${{ secrets.HOST_NAME }}
               User ${{ secrets.USER_NAME }}
               IdentityFile ~/.ssh/github-actions
       - name: run
         run: ssh server "echo 'hogehoge'"
