name: CI        #Workflow の名前何でもOK

on:             #実行されるタイミングを設定
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:           #以下が実行される内容
  SSH:
    runs-on: ubuntu-latest  #実行環境を指定
      
    steps:
    - name: sshToPr
      run: ssh -i ${{ secrets.PRIVATE_KEY }} nakamura@nakamura-FMVS14001
