name: Docker Image CI_LS

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: GitFetch
      run: git fetch -p

    - name: GitCheckout
      run: git checkout master_20231026

#    - name: Build the Docker image
#      run: docker build . --file /home/runner/work/test20231024/test20231024/sample/Dockerfile --tag getting-started2:$(date +%s)

#    - name: DcImg
#      run: docker images

    - name: Ls
      run: ls -lrt

    - name: Diff
#      run: diff -s ./python-image.tar.gz ./python-image2.tar.gz > /dev/null 2>&1
      run: git diff -- ./python-image.tar.gz ./python-image2.tar.gz

    - name: CompareFile
      run: |
        ls -lrt
#        diff -s python-image.tar.gz python-image2.tar.gz > /dev/null 2>&1
#        if [ $? -eq 0 ]; then
#          echo "同じファイルです"
#        elif [ $? -eq 1 ]; then
#          echo "違うファイルです"
#        fi

