name: Docker Image CI_LS

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: LfsLsFiles
      run: git lfs ls-files

    - name: Mkdir
      run: sudo mkdir /tmp_contents

    - name: Ls
      run: ls -lrt /

    - uses: actions/checkout@v3

    - name: GitFetch
      run: git fetch -p

    # ブランチmaster_20231026の資材(一つ前のバックアップ資材を想定)を/tmp_contentsフォルダに格納する
    - name: GitCheckout
      run: git checkout master_20231026
#    - name: CpContents
#      run: sudo cp -r . /tmp_contents
#    - name: Ls
#      run: ls -lrt /tmp_contents
#    - name: Ls
#      run: ls -lrt

#    # ブランチmaster_20231205(最新のバックアップ資材を想定)に切り替える
#    - name: GitCheckout
#      run: git checkout master_20231205
#    - name: Ls
#      run: ls -lrt /tmp_contents
#    - name: Ls
#      run: ls -lrt

#    - name: Build the Docker image
#      run: docker build . --file /home/runner/work/test20231205/test20231205/sample_python/Dockerfile -t python-image
#    - name: DcImg
#      run: docker images
#    - name: DcSave
#      run: docker save python-image | gzip > /home/runner/work/test20231205/test20231205/python-image.tar.gz
#      run: docker save python-image > /home/runner/work/test20231205/test20231205/python-image.tar
#    - name: Ls
#      run: ls -lrt /tmp_contents
#    - name: Ls
#      run: ls -lrt


      
#    - name: Build the Docker image
#      run: docker build . --file /home/runner/work/test20231024/test20231024/sample/Dockerfile --tag getting-started2:$(date +%s)

#    - name: DcImg
#      run: docker images

#    - name: Diff
#      run: diff -s ./python-image.tar.gz ./python-image2.tar.gz > /dev/null 2>&1
#      run: git diff -- ./python-image.tar.gz ./python-image2.tar.gz

#    - name: CompareFile
#      run: |
#        ls -lrt
#        diff -s python-image.tar.gz python-image2.tar.gz > /dev/null 2>&1
#        if [ $? -eq 0 ]; then
#          echo "同じファイルです"
#        elif [ $? -eq 1 ]; then
#          echo "違うファイルです"
#        fi

