name: Redhat Test

on:
  workflow_dispatch:

permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: DL oc-mirror.tar.gz
      run: |
        ls -lrt
        wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.tar.gz
        wget https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
        ls -lrt

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v3
#      with:
#         name: FilePath
#         path: python-image-all.tar
